export interface CreditNoteProduct {
    id?,
    save?,
    product?,
    idInvoice?,
    idProduct?;
    code?;
    description?;
    quantity?;
    unitValue?,
    discount?,
    amount?
    mw?,
    percentageIva?,
    amountIva?,
    taxiKey?,
    typeFactor?,
    base?,
    rateQuota?,
    idTypeDocument?,
    idSettlementInvoice?,
    idConcept?,
    unityText?,
    unityKey?,
    codeClient?,
    folioUnique?,
    concept?
    originalAmount?,
    modifiedAmount?,
    amountAjust?,
    iva?,
    total?,
    amountLetter?;
    folioUnique2?;
    concept2?;
    originalAmount2?;
    modifiedAmount2?;
    amountAjust2?;
    iva2?;
    total2?;
    amountLetter2?;
}
