export interface InvoiceProduct {
    id?,
    save?,
    product?,
    serie?;
    number?;
    idPlantBranchOffice?;
    idSys?;
    idProduct?;
    code?;
    description?;
    quantity?;
    unitValue?,
    discount?,
    amount?
    mw?,
    percentageIva?,
    amountIva?,
    taxiKey?,
    typeFactor?,
    base?,
    rateQuota?,
    idTypeDocument?,
    idDocumentControl?,
    idDocumentControlDetail?,
    unityText?,
    unityKey?,
    codeClient?,
    folioUnique?,
    concept?
}
