export interface Invoice {
    number?,
    serie?,
    idPlantBranchOffice?;
    idSys?,
    save?
    yearMarket?
    monthMarket?;
    dayMarket?;
    yearClosing?;
    monthClosing?;
    invoice?;
    idStatus?;
    idStatusPayment?;
    folioCfd?;
    date?;
    idMoney?;
    exchangeRate?;
    idClient?;
    client?;
    emails?;
    idPaymentWay?;
    account?;
    creditDays?;
    purchaseOrder?;
    idPaymentCondition?;
    idUseCfdi?;
    idPaymentMethod?;
    confirmationSat?;
    paymentConditions?;
    idTypeRelation?;
    idTypeInvoice?;
    subtotal?;
    percentageDiscount?;
    discountAmount?;
    subtotal2?;
    amountRateIvaTransfer?;
    total?;
    observations?;
    stampingDate?;
    stampingHour;
    cancellationDate?;
    cancellationHour?;
    dateSchippingInvoice?;
    seal?;
    originalString?;
    uuid?;
    certificate?;
    certificateNumber?;
    xml?;
    xmlCancellation?;
    idPlantFiscalData?;
    idPlantDirection?;
    idClientFiscalData?;
    cp?;
    fuf?;
    accountOrder?;
    fuecd?;
    ful?;
    periodEdc?;
    dayOperation?;
    fiscalRegime?;
    paymentDeadline?;
    participantCenace?;
    bank?;
    branchOffice?;
    clabe?;
    reference?;
    contact?;
    rfcProvCertif?;
    invoiceProducts;
}
