export interface Product {
    id?;
    code?;
    name?;
    description?;
    active?;
    price?;
    idRateIvaSat?;
    rateIvaSat?;
    idRetentionIvaSat?;
    retentionIvaSat?;
    idProductSat?;
    productSat?;
    idUnityProduct?;
    unityProduct?;
    idTypeProduct?;
    typeProduct?;
    save?;
    sys?;
    system?;
}
